"""
LangGraph node wrappers for the Finance Agentic AI System.

Each node has one orchestration responsibility:

1. Read the required input from FinanceGraphState.
2. Call one existing agent.
3. Store the agent output back into the shared state.
4. Record execution errors safely.

This module must not duplicate finance calculations or agent business logic.
"""

from __future__ import annotations

from typing import Any

import pandas as pd

from src.agents.analytics.anomaly_agent import AnomalyAgent
from src.agents.analytics.operations_analysis_agent import (
    OperationsAnalysisAgent,
)
from src.agents.analytics.recommendation_agent import RecommendationAgent
from src.agents.analytics.root_cause_agent import RootCauseAgent
from src.agents.data_quality.cleaning_agent import CleaningAgent
from src.agents.data_quality.profiling_agent import ProfilingAgent
from src.agents.data_quality.validation_agent import ValidationAgent
from src.agents.finance.budget_agent import BudgetAgent
from src.agents.finance.finance_rules_agent import FinanceRulesAgent
from src.agents.finance.forecast_agent import ForecastAgent
from src.agents.finance.kpi_agent import KPIAgent
from src.agents.finance.pnl_agent import PnlAgent
from src.agents.finance.scenario_agent import ScenarioAgent
from src.agents.finance.variance_agent import RevenueVarianceAgent
from src.agents.reporting.commentary_agent import CommentaryAgent
from src.agents.reporting.report_agent import ReportAgent
from src.orchestrator.state import FinanceGraphState


DEFAULT_KPIS = [
    "total_orders",
    "completed_orders",
    "cancelled_orders",
    "fulfillment_percentage",
    "cancellation_percentage",
    "actual_revenue",
    "actual_aov",
    "budget_orders",
    "budget_revenue",
    "budget_aov",
    "revenue_variance",
    "forecast_orders",
    "forecast_revenue",
    "forecast_aov",
    "scenario_orders",
    "scenario_revenue",
    "finance_rules_status",
]


# ----------------------------------------------------------------------
# Shared node helpers
# ----------------------------------------------------------------------


def _record_success(
    state: FinanceGraphState,
    node_name: str,
    **updates: Any,
) -> FinanceGraphState:
    """
    Return a successful state update while preserving existing state.

    Args:
        state:
            Current graph state.

        node_name:
            Name of the successfully completed node.

        **updates:
            New state values generated by the node.

    Returns:
        Updated FinanceGraphState.
    """

    executed_nodes = list(state.get("executed_nodes", []))

    if node_name not in executed_nodes:
        executed_nodes.append(node_name)

    return {
        **state,
        **updates,
        "execution_status": "running",
        "error_message": "",
        "failed_node": "",
        "errors": list(state.get("errors", [])),
        "executed_nodes": executed_nodes,
    }


def _record_failure(
    state: FinanceGraphState,
    node_name: str,
    error: Exception | str,
) -> FinanceGraphState:
    """
    Store a node failure in the shared state.

    Args:
        state:
            Current graph state.

        node_name:
            Name of the node that failed.

        error:
            Exception or error message.

    Returns:
        Failed FinanceGraphState.
    """

    error_message = str(error)
    errors = list(state.get("errors", []))
    errors.append(f"{node_name}: {error_message}")

    return {
        **state,
        "execution_status": "failed",
        "failed_node": node_name,
        "error_message": error_message,
        "errors": errors,
    }


def _require_dataframe(
    state: FinanceGraphState,
    field_name: str,
    node_name: str,
) -> pd.DataFrame:
    """
    Retrieve and validate a required DataFrame from state.

    Raises:
        ValueError:
            If the field is missing or the DataFrame is empty.

        TypeError:
            If the field is not a pandas DataFrame.
    """

    value = state.get(field_name)

    if value is None:
        raise ValueError(
            f"Required state field '{field_name}' is missing."
        )

    if not isinstance(value, pd.DataFrame):
        raise TypeError(
            f"State field '{field_name}' must be a pandas DataFrame "
            f"for node '{node_name}'."
        )

    if value.empty:
        raise ValueError(
            f"State field '{field_name}' contains an empty DataFrame."
        )

    return value


def _require_state_value(
    state: FinanceGraphState,
    field_name: str,
) -> Any:
    """
    Retrieve a required result from state.

    Raises:
        ValueError:
            If the required value is missing.
    """

    value = state.get(field_name)

    if value is None:
        raise ValueError(
            f"Required state field '{field_name}' is missing."
        )

    return value


def _get_filters(state: FinanceGraphState) -> dict[str, Any]:
    """Return graph filters or an empty dictionary."""

    filters = state.get("filters", {})

    if filters is None:
        return {}

    if not isinstance(filters, dict):
        raise TypeError("State field 'filters' must be a dictionary.")

    return filters


def _get_group_by(
    state: FinanceGraphState,
    default: str = "month",
) -> str:
    """Return a valid single group-by value from state."""

    group_by = state.get("group_by")

    if group_by is None:
        return default

    if not isinstance(group_by, str):
        raise TypeError(
            "State field 'group_by' must be a string for the current agents."
        )

    return group_by


# ----------------------------------------------------------------------
# Validation nodes
# ----------------------------------------------------------------------


def validate_operations_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Validate raw operations data."""

    node_name = "validate_operations"

    try:
        operations_data = _require_dataframe(
            state,
            "operations_data",
            node_name,
        )

        validation_result = ValidationAgent.validate_operations_data(
            operations_data
        )

        if not validation_result.is_valid:
            details = "; ".join(validation_result.errors)
            raise ValueError(
                "Operations validation failed: "
                f"{details or 'Unknown validation error.'}"
            )

        return _record_success(
            state,
            node_name,
            operations_validation=validation_result,
            validation_result=validation_result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def validate_budget_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Validate raw budget data."""

    node_name = "validate_budget"

    try:
        budget_data = _require_dataframe(
            state,
            "budget_data",
            node_name,
        )

        validation_result = ValidationAgent.validate_budget_data(
            budget_data
        )

        if not validation_result.is_valid:
            details = "; ".join(validation_result.errors)
            raise ValueError(
                "Budget validation failed: "
                f"{details or 'Unknown validation error.'}"
            )

        return _record_success(
            state,
            node_name,
            budget_validation=validation_result,
            validation_result=validation_result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


# ----------------------------------------------------------------------
# Cleaning nodes
# ----------------------------------------------------------------------


def clean_operations_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Clean validated operations data."""

    node_name = "clean_operations"

    try:
        _require_state_value(state, "operations_validation")

        operations_data = _require_dataframe(
            state,
            "operations_data",
            node_name,
        )

        cleaned_data = CleaningAgent.clean_operations_data(
            operations_data
        )

        if cleaned_data.empty:
            raise ValueError(
                "Operations cleaning produced an empty DataFrame."
            )

        return _record_success(
            state,
            node_name,
            cleaned_operations_data=cleaned_data,
            cleaned_data=cleaned_data,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def clean_budget_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Clean validated budget data."""

    node_name = "clean_budget"

    try:
        _require_state_value(state, "budget_validation")

        budget_data = _require_dataframe(
            state,
            "budget_data",
            node_name,
        )

        cleaned_data = CleaningAgent.clean_budget_data(budget_data)

        if cleaned_data.empty:
            raise ValueError(
                "Budget cleaning produced an empty DataFrame."
            )

        return _record_success(
            state,
            node_name,
            cleaned_budget_data=cleaned_data,
            cleaned_data=cleaned_data,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


# ----------------------------------------------------------------------
# Profiling nodes
# ----------------------------------------------------------------------


def profile_operations_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Profile cleaned operations data."""

    node_name = "profile_operations"

    try:
        cleaned_data = _require_dataframe(
            state,
            "cleaned_operations_data",
            node_name,
        )

        profile_result = ProfilingAgent.profile_operations_data(
            cleaned_data
        )

        return _record_success(
            state,
            node_name,
            operations_profile=profile_result,
            profile_result=profile_result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def profile_budget_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Profile cleaned budget data."""

    node_name = "profile_budget"

    try:
        cleaned_data = _require_dataframe(
            state,
            "cleaned_budget_data",
            node_name,
        )

        profile_result = ProfilingAgent.profile_budget_data(
            cleaned_data
        )

        return _record_success(
            state,
            node_name,
            budget_profile=profile_result,
            profile_result=profile_result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


# ----------------------------------------------------------------------
# Analysis nodes
# ----------------------------------------------------------------------


def operations_analysis_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing OperationsAnalysisAgent."""

    node_name = "operations_analysis"

    try:
        cleaned_data = _require_dataframe(
            state,
            "cleaned_operations_data",
            node_name,
        )

        filters = _get_filters(state)
        group_by = _get_group_by(
            state,
            default=state.get("frequency", "month"),
        )

        result = OperationsAnalysisAgent().analyze(
            data=cleaned_data,
            start_date=state.get("start_date"),
            end_date=state.get("end_date"),
            vehicle_category=filters.get("vehicle_category"),
            pickup_cluster=filters.get("pickup_cluster"),
            group_by=group_by,
        )

        return _record_success(
            state,
            node_name,
            operations_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def budget_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing BudgetAgent."""

    node_name = "budget"

    try:
        cleaned_data = _require_dataframe(
            state,
            "cleaned_budget_data",
            node_name,
        )

        filters = _get_filters(state)
        group_by = _get_group_by(
            state,
            default=state.get("frequency", "month"),
        )

        result = BudgetAgent().analyze(
            data=cleaned_data,
            start_month=state.get("start_month"),
            end_month=state.get("end_month"),
            vehicle_category=filters.get("vehicle_category"),
            group_by=group_by,
        )

        return _record_success(
            state,
            node_name,
            budget_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def forecast_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing ForecastAgent."""

    node_name = "forecast"

    try:
        operations_result = _require_state_value(
            state,
            "operations_result",
        )

        period_summary = getattr(
            operations_result,
            "period_summary",
            None,
        )

        if not period_summary:
            raise ValueError(
                "Operations result does not contain a usable period summary."
            )

        result = ForecastAgent().analyze(
            period_summary=period_summary,
            frequency=state.get("frequency", "month"),
            rolling_window=state.get("rolling_window", 3),
            forecast_periods=state.get("forecast_periods", 3),
        )

        forecast_summary = getattr(
            result,
            "forecast_summary",
            None,
        )

        if not forecast_summary:
            raise ValueError(
                "Forecast Agent produced an empty forecast output."
            )

        return _record_success(
            state,
            node_name,
            forecast_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def scenario_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing ScenarioAgent."""

    node_name = "scenario"

    try:
        forecast_result = _require_state_value(
            state,
            "forecast_result",
        )

        assumptions = state.get("business_assumptions")

        if assumptions is None:
            raise ValueError(
                "Required state field 'business_assumptions' is missing."
            )

        if isinstance(assumptions, pd.DataFrame) and assumptions.empty:
            raise ValueError(
                "Business assumptions DataFrame is empty."
            )

        if isinstance(assumptions, list) and not assumptions:
            raise ValueError(
                "Business assumptions list is empty."
            )

        result = ScenarioAgent().analyze(
            forecast_result=forecast_result,
            assumptions=assumptions,
            scenario_name=state.get(
                "scenario_name",
                "Management Case",
            ),
        )

        adjusted_forecast = getattr(
            result,
            "adjusted_forecast",
            None,
        )

        if not adjusted_forecast:
            raise ValueError(
                "Scenario Agent produced an empty scenario output."
            )

        return _record_success(
            state,
            node_name,
            scenario_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def variance_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing RevenueVarianceAgent."""

    node_name = "variance"

    try:
        operations_result = _require_state_value(
            state,
            "operations_result",
        )
        budget_result = _require_state_value(
            state,
            "budget_result",
        )

        result = RevenueVarianceAgent().analyze(
            actual_result=operations_result,
            budget_result=budget_result,
        )

        return _record_success(
            state,
            node_name,
            variance_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)



def pnl_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """
    Run the existing PnlAgent.

    The node uses cleaned operations and budget data produced by the existing
    validation and cleaning nodes. Corporate-expense datasets are passed
    directly to PnlAgent, which remains responsible for validating and
    preparing those P&L-specific inputs.

    The complete agent result is stored in ``pnl_result``. Its structured
    outputs are also copied into dedicated state fields so FastAPI, Streamlit,
    RAG, and chatbot response-building layers can access them directly.
    """

    node_name = "pnl"

    try:
        cleaned_operations_data = _require_dataframe(
            state,
            "cleaned_operations_data",
            node_name,
        )
        cleaned_budget_data = _require_dataframe(
            state,
            "cleaned_budget_data",
            node_name,
        )
        corporate_expenses_data = _require_dataframe(
            state,
            "corporate_expenses_data",
            node_name,
        )
        budget_corporate_expenses_data = _require_dataframe(
            state,
            "budget_corporate_expenses_data",
            node_name,
        )

        result = PnlAgent().analyze(
            operations_data=cleaned_operations_data,
            budget_data=cleaned_budget_data,
            corporate_expenses_data=corporate_expenses_data,
            budget_corporate_expenses_data=(
                budget_corporate_expenses_data
            ),
            start_month=state.get("start_month"),
            end_month=state.get("end_month"),
        )

        actual_pnl = getattr(result, "actual_pnl", None)
        budget_pnl = getattr(result, "budget_pnl", None)
        variance_pnl = getattr(result, "variance_pnl", None)

        pnl_summary = getattr(
            result,
            "pnl_summary",
            getattr(result, "summary", None),
        )
        available_months = getattr(
            result,
            "available_months",
            [],
        )
        excluded_actual_months = getattr(
            result,
            "excluded_actual_months",
            [],
        )
        excluded_budget_months = getattr(
            result,
            "excluded_budget_months",
            [],
        )

        if actual_pnl is None:
            raise ValueError(
                "P&L Agent result does not contain 'actual_pnl'."
            )

        if budget_pnl is None:
            raise ValueError(
                "P&L Agent result does not contain 'budget_pnl'."
            )

        if variance_pnl is None:
            raise ValueError(
                "P&L Agent result does not contain 'variance_pnl'."
            )

        if pnl_summary is None:
            raise ValueError(
                "P&L Agent result does not contain a P&L summary."
            )

        return _record_success(
            state,
            node_name,
            pnl_result=result,
            actual_pnl=actual_pnl,
            budget_pnl=budget_pnl,
            variance_pnl=variance_pnl,
            pnl_summary=pnl_summary,
            pnl_available_months=list(available_months),
            pnl_excluded_actual_months=list(
                excluded_actual_months
            ),
            pnl_excluded_budget_months=list(
                excluded_budget_months
            ),
        )

    except Exception as error:
        return _record_failure(state, node_name, error)



def finance_rules_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing FinanceRulesAgent."""

    node_name = "finance_rules"

    try:
        available_results = [
            state.get("operations_result"),
            state.get("budget_result"),
            state.get("variance_result"),
            state.get("forecast_result"),
            state.get("scenario_result"),
        ]

        if all(result is None for result in available_results):
            raise ValueError(
                "Finance Rules Agent requires at least one available "
                "finance or analytics result."
            )

        result = FinanceRulesAgent().analyze(
            operations_result=state.get("operations_result"),
            budget_result=state.get("budget_result"),
            revenue_variance_result=state.get("variance_result"),
            forecast_result=state.get("forecast_result"),
            scenario_result=state.get("scenario_result"),
        )

        return _record_success(
            state,
            node_name,
            finance_rules_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def anomaly_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing AnomalyAgent."""

    node_name = "anomaly"

    try:
        operations_result = _require_state_value(
            state,
            "operations_result",
        )

        filters = _get_filters(state)

        result = AnomalyAgent().analyze(
            operations_result=operations_result,
            levels=filters.get("anomaly_levels"),
            metrics=filters.get("anomaly_metrics"),
        )

        return _record_success(
            state,
            node_name,
            anomaly_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def root_cause_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing RootCauseAgent."""

    node_name = "root_cause"

    try:
        anomaly_result = _require_state_value(
            state,
            "anomaly_result",
        )
        operations_result = _require_state_value(
            state,
            "operations_result",
        )

        result = RootCauseAgent().analyze(
            anomaly_result=anomaly_result,
            operations_result=operations_result,
            variance_result=state.get("variance_result"),
        )

        return _record_success(
            state,
            node_name,
            root_cause_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def recommendation_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing RecommendationAgent."""

    node_name = "recommendation"

    try:
        root_cause_result = _require_state_value(
            state,
            "root_cause_result",
        )

        result = RecommendationAgent().analyze(
            root_cause_result
        )

        return _record_success(
            state,
            node_name,
            recommendation_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def kpi_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing KPIAgent."""

    node_name = "kpi"

    try:
        selected_flow = state.get("selected_flow", "unknown")

        requested_kpis = state.get("requested_kpis")

        if not requested_kpis:
            if selected_flow == "forecast":
                requested_kpis = [
                    "forecast_orders",
                    "forecast_revenue",
                    "forecast_aov",
                ]
            elif selected_flow == "kpi":
                requested_kpis = [
                    "total_orders",
                    "completed_orders",
                    "cancelled_orders",
                    "fulfillment_percentage",
                    "cancellation_percentage",
                    "actual_revenue",
                    "actual_aov",
                ]
            else:
                requested_kpis = DEFAULT_KPIS

        forecast_period = None
        scenario_period = None

        forecast_result = state.get("forecast_result")

        if forecast_result is not None:
            forecast_summary = getattr(
                forecast_result,
                "forecast_summary",
                None,
            )

            if forecast_summary:
                forecast_period = str(
                    forecast_summary[0]["forecast_period"]
                )

        scenario_result = state.get("scenario_result")

        if scenario_result is not None:
            adjusted_forecast = getattr(
                scenario_result,
                "adjusted_forecast",
                None,
            )

            if adjusted_forecast:
                scenario_period = str(
                    adjusted_forecast[0]["forecast_period"]
                )

        filters = _get_filters(state)

        result = KPIAgent().analyze(
            requested_kpis=requested_kpis,
            operations_result=state.get("operations_result"),
            budget_result=state.get("budget_result"),
            revenue_variance_result=state.get("variance_result"),
            forecast_result=forecast_result,
            scenario_result=scenario_result,
            finance_rules_result=state.get("finance_rules_result"),
            forecast_period=forecast_period,
            scenario_period=scenario_period,
            dimension=filters.get("dimension"),
            dimension_value=filters.get("dimension_value"),
        )

        return _record_success(
            state,
            node_name,
            requested_kpis=requested_kpis,
            kpi_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def commentary_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing CommentaryAgent."""

    node_name = "commentary"

    try:
        kpi_result = _require_state_value(
            state,
            "kpi_result",
        )

        result = CommentaryAgent().analyze(
            kpi_result=kpi_result,
            revenue_variance_result=state.get("variance_result"),
            forecast_result=state.get("forecast_result"),
            scenario_result=state.get("scenario_result"),
            finance_rules_result=state.get("finance_rules_result"),
        )

        return _record_success(
            state,
            node_name,
            commentary_result=result,
        )

    except Exception as error:
        return _record_failure(state, node_name, error)


def report_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """Run the existing ReportAgent and complete graph execution."""

    node_name = "report"

    try:
        commentary_result = _require_state_value(
            state,
            "commentary_result",
        )

        result = ReportAgent().analyze(
            commentary_result=commentary_result,
            operations_result=state.get("operations_result"),
            kpi_result=state.get("kpi_result"),
            budget_result=state.get("budget_result"),
            forecast_result=state.get("forecast_result"),
            variance_result=state.get("variance_result"),
            anomaly_result=state.get("anomaly_result"),
            root_cause_result=state.get("root_cause_result"),
            recommendation_result=state.get("recommendation_result"),
            finance_rules_result=state.get("finance_rules_result"),
            scenario_result=state.get("scenario_result"),
            report_title="Finance Agentic AI Management Report",
            report_type=state.get("selected_flow", "management"),
        )

        successful_state = _record_success(
            state,
            node_name,
            report_result=result,
        )

        return {
            **successful_state,
            "execution_status": "completed",
        }

    except Exception as error:
        return _record_failure(state, node_name, error)


# ----------------------------------------------------------------------
# Graph control nodes
# ----------------------------------------------------------------------


def complete_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """
    Mark a successful route as completed.

    This is useful for routes such as budget, KPI, or forecast that may end
    without creating a complete management report.
    """

    if state.get("execution_status") == "failed":
        return state

    executed_nodes = list(state.get("executed_nodes", []))

    if "complete" not in executed_nodes:
        executed_nodes.append("complete")

    return {
        **state,
        "execution_status": "completed",
        "error_message": "",
        "failed_node": "",
        "executed_nodes": executed_nodes,
    }


def error_node(
    state: FinanceGraphState,
) -> FinanceGraphState:
    """
    Preserve a failed state before LangGraph execution ends.

    Individual nodes already record the original exception. This node ensures
    the graph ends with a consistent failed status.
    """

    errors = list(state.get("errors", []))
    error_message = state.get(
        "error_message",
        "Graph execution failed.",
    )

    if not error_message:
        error_message = "Graph execution failed."

    return {
        **state,
        "execution_status": "failed",
        "error_message": error_message,
        "errors": errors,
    }


def should_continue(state: FinanceGraphState) -> str:
    """
    Return the conditional graph route after any agent node.

    Returns:
        ``continue`` when execution can proceed.
        ``error`` when a previous node failed.
    """

    if state.get("execution_status") == "failed":
        return "error"

    return "continue"