"""
P&L Commentary Agent for the Finance Agentic AI System.

This module converts the summary generated by PnlAgent into deterministic,
management-friendly financial commentary.

It does not:

- Recalculate P&L values
- Modify P&L results
- Call an LLM
- Invent unsupported business explanations

The agent consumes:

    PnlAnalysisResult.summary

Expected structure:

    {
        "actual": {...},
        "budget": {...},
        "variance": {...},
    }
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping


@dataclass(slots=True)
class PnlCommentaryResult:
    """
    Store management commentary generated from a P&L result.

    Attributes:
        executive_summary:
            Consolidated management-level P&L summary.

        revenue_commentary:
            Actual versus budget revenue commentary.

        profitability_commentary:
            Gross profit, EBITDA, EBIT, and EBT commentary.

        cost_commentary:
            Direct cost and operating-expense commentary.

        margin_commentary:
            Gross-margin movement commentary.

        positive_drivers:
            Favourable financial outcomes.

        risks:
            Unfavourable financial outcomes.

        management_attention:
            Financial areas requiring management review.

        source_summary:
            Original P&L summary used to generate commentary.
    """

    executive_summary: str
    revenue_commentary: list[str] = field(default_factory=list)
    profitability_commentary: list[str] = field(default_factory=list)
    cost_commentary: list[str] = field(default_factory=list)
    margin_commentary: list[str] = field(default_factory=list)
    positive_drivers: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    management_attention: list[str] = field(default_factory=list)
    source_summary: dict[str, Any] = field(default_factory=dict)


class PnlCommentaryAgent:
    """
    Generate deterministic management commentary from P&L results.

    Variance conventions:

        Revenue and profit:
            Positive variance = favourable
            Negative variance = unfavourable

        Costs and expenses:
            Negative variance = favourable
            Positive variance = unfavourable

        Gross margin:
            Positive percentage-point variance = favourable
            Negative percentage-point variance = unfavourable
    """

    MATERIAL_VARIANCE_PERCENTAGE = 10.0
    LARGE_VARIANCE_PERCENTAGE = 20.0
    MATERIAL_MARGIN_MOVEMENT = 1.0

    def analyze(
        self,
        pnl_result: Any,
    ) -> PnlCommentaryResult:
        """
        Generate P&L management commentary.

        Args:
            pnl_result:
                PnlAnalysisResult returned by PnlAgent.

        Returns:
            PnlCommentaryResult containing structured commentary.

        Raises:
            ValueError:
                If pnl_result or its summary is missing or invalid.
        """

        summary = self._extract_summary(pnl_result)

        actual = summary["actual"]
        budget = summary["budget"]
        variance = summary["variance"]

        revenue_commentary = self._generate_revenue_commentary(
            actual=actual,
            budget=budget,
            variance=variance,
        )

        profitability_commentary = (
            self._generate_profitability_commentary(
                actual=actual,
                budget=budget,
                variance=variance,
            )
        )

        cost_commentary = self._generate_cost_commentary(
            actual=actual,
            budget=budget,
            variance=variance,
        )

        margin_commentary = self._generate_margin_commentary(
            actual=actual,
            budget=budget,
            variance=variance,
        )

        positive_drivers = self._identify_positive_drivers(
            variance=variance,
        )

        risks = self._identify_risks(
            variance=variance,
        )

        management_attention = (
            self._identify_management_attention(
                variance=variance,
            )
        )

        executive_summary = self._generate_executive_summary(
            actual=actual,
            budget=budget,
            variance=variance,
        )

        return PnlCommentaryResult(
            executive_summary=executive_summary,
            revenue_commentary=revenue_commentary,
            profitability_commentary=profitability_commentary,
            cost_commentary=cost_commentary,
            margin_commentary=margin_commentary,
            positive_drivers=positive_drivers,
            risks=risks,
            management_attention=management_attention,
            source_summary=self._copy_summary(summary),
        )

    def _extract_summary(
        self,
        pnl_result: Any,
    ) -> dict[str, Mapping[str, Any]]:
        """
        Extract and validate the summary from a P&L result.
        """

        if pnl_result is None:
            raise ValueError("pnl_result is required.")

        summary = getattr(pnl_result, "summary", None)

        if summary is None and isinstance(pnl_result, Mapping):
            summary = pnl_result.get("summary")

        if not isinstance(summary, Mapping):
            raise ValueError(
                "pnl_result must contain a valid summary dictionary."
            )

        required_sections = ("actual", "budget", "variance")

        missing_sections = [
            section
            for section in required_sections
            if section not in summary
        ]

        if missing_sections:
            raise ValueError(
                "P&L summary is missing required sections: "
                f"{missing_sections}"
            )

        for section in required_sections:
            if not isinstance(summary[section], Mapping):
                raise TypeError(
                    f"P&L summary section '{section}' must be a mapping."
                )

        return {
            "actual": summary["actual"],
            "budget": summary["budget"],
            "variance": summary["variance"],
        }

    def _generate_executive_summary(
        self,
        actual: Mapping[str, Any],
        budget: Mapping[str, Any],
        variance: Mapping[str, Any],
    ) -> str:
        """
        Generate concise management-level P&L commentary.
        """

        sentences: list[str] = []

        actual_revenue = self._get_number(actual, "revenue")
        revenue_variance = self._get_number(
            variance,
            "revenue_variance",
        )

        actual_gross_profit = self._get_number(
            actual,
            "gross_profit",
        )

        gross_margin = self._get_number(
            actual,
            "gross_margin_percentage",
        )

        margin_variance = self._get_number(
            variance,
            "gross_margin_percentage_point_variance",
        )

        actual_ebitda = self._get_number(actual, "ebitda")
        ebitda_variance = self._get_number(
            variance,
            "ebitda_variance",
        )

        actual_ebt = self._get_number(actual, "ebt")
        ebt_variance = self._get_number(
            variance,
            "ebt_variance",
        )

        sentences.append(
            "Actual revenue was "
            f"{self._format_currency(actual_revenue)}"
            f"{self._describe_profit_variance_inline(revenue_variance)}."
        )

        sentences.append(
            "Gross profit reached "
            f"{self._format_currency(actual_gross_profit)}, "
            "with a gross margin of "
            f"{self._format_percentage(gross_margin)}"
            f"{self._describe_margin_variance_inline(margin_variance)}."
        )

        sentences.append(
            "EBITDA was "
            f"{self._format_currency(actual_ebitda)}"
            f"{self._describe_profit_variance_inline(ebitda_variance)}."
        )

        sentences.append(
            "EBT was "
            f"{self._format_currency(actual_ebt)}"
            f"{self._describe_profit_variance_inline(ebt_variance)}."
        )

        return " ".join(sentences)

    def _generate_revenue_commentary(
        self,
        actual: Mapping[str, Any],
        budget: Mapping[str, Any],
        variance: Mapping[str, Any],
    ) -> list[str]:
        """
        Generate revenue actual-versus-budget commentary.
        """

        actual_revenue = self._get_number(actual, "revenue")
        budget_revenue = self._get_number(budget, "revenue")

        revenue_variance = self._get_number(
            variance,
            "revenue_variance",
        )

        revenue_variance_percentage = self._get_number(
            variance,
            "revenue_variance_percentage",
        )

        if revenue_variance > 0:
            performance = "above"
            classification = "favourable"
        elif revenue_variance < 0:
            performance = "below"
            classification = "unfavourable"
        else:
            return [
                "Actual revenue was in line with budget at "
                f"{self._format_currency(actual_revenue)}."
            ]

        return [
            "Actual revenue was "
            f"{self._format_currency(actual_revenue)}, compared with "
            f"budget revenue of {self._format_currency(budget_revenue)}.",
            "Revenue was "
            f"{performance} budget by "
            f"{self._format_currency(abs(revenue_variance))}, representing "
            f"a {self._format_percentage(abs(revenue_variance_percentage))} "
            f"{classification} variance.",
        ]

    def _generate_profitability_commentary(
        self,
        actual: Mapping[str, Any],
        budget: Mapping[str, Any],
        variance: Mapping[str, Any],
    ) -> list[str]:
        """
        Generate gross profit, EBITDA, EBIT, and EBT commentary.
        """

        comments: list[str] = []

        metrics = (
            ("gross_profit", "Gross profit"),
            ("ebitda", "EBITDA"),
            ("ebit", "EBIT"),
            ("ebt", "EBT"),
        )

        for metric, display_name in metrics:
            actual_value = self._get_number(actual, metric)
            budget_value = self._get_number(budget, metric)

            variance_value = self._get_number(
                variance,
                f"{metric}_variance",
            )

            variance_percentage = self._get_number(
                variance,
                f"{metric}_variance_percentage",
            )

            comments.append(
                self._build_profit_commentary(
                    display_name=display_name,
                    actual_value=actual_value,
                    budget_value=budget_value,
                    variance_value=variance_value,
                    variance_percentage=variance_percentage,
                )
            )

        return comments

    def _generate_cost_commentary(
        self,
        actual: Mapping[str, Any],
        budget: Mapping[str, Any],
        variance: Mapping[str, Any],
    ) -> list[str]:
        """
        Generate commentary for direct cost and operating expenses.

        For cost metrics:

            Actual below budget = favourable
            Actual above budget = unfavourable
        """

        comments: list[str] = []

        metrics = (
            ("direct_cost", "Direct cost"),
            ("sales_marketing", "Sales and marketing expense"),
            ("other_opex", "Other operating expense"),
            ("depreciation", "Depreciation"),
            ("interest", "Interest expense"),
        )

        for metric, display_name in metrics:
            actual_value = self._get_number(actual, metric)
            budget_value = self._get_number(budget, metric)

            variance_value = self._get_number(
                variance,
                f"{metric}_variance",
            )

            variance_percentage = self._get_number(
                variance,
                f"{metric}_variance_percentage",
            )

            comments.append(
                self._build_cost_commentary(
                    display_name=display_name,
                    actual_value=actual_value,
                    budget_value=budget_value,
                    variance_value=variance_value,
                    variance_percentage=variance_percentage,
                )
            )

        return comments

    def _generate_margin_commentary(
        self,
        actual: Mapping[str, Any],
        budget: Mapping[str, Any],
        variance: Mapping[str, Any],
    ) -> list[str]:
        """
        Generate gross-margin percentage-point commentary.
        """

        actual_margin = self._get_number(
            actual,
            "gross_margin_percentage",
        )

        budget_margin = self._get_number(
            budget,
            "gross_margin_percentage",
        )

        margin_variance = self._get_number(
            variance,
            "gross_margin_percentage_point_variance",
        )

        if margin_variance > 0:
            return [
                "Gross margin improved from "
                f"{self._format_percentage(budget_margin)} to "
                f"{self._format_percentage(actual_margin)}, a favourable "
                f"movement of "
                f"{self._format_percentage_points(margin_variance)}."
            ]

        if margin_variance < 0:
            return [
                "Gross margin declined from "
                f"{self._format_percentage(budget_margin)} to "
                f"{self._format_percentage(actual_margin)}, an "
                f"unfavourable movement of "
                f"{self._format_percentage_points(abs(margin_variance))}."
            ]

        return [
            "Gross margin was in line with budget at "
            f"{self._format_percentage(actual_margin)}."
        ]

    def _identify_positive_drivers(
        self,
        variance: Mapping[str, Any],
    ) -> list[str]:
        """
        Identify favourable P&L outcomes.
        """

        drivers: list[str] = []

        favourable_profit_metrics = (
            ("revenue_variance", "Revenue exceeded budget."),
            (
                "gross_profit_variance",
                "Gross profit exceeded budget.",
            ),
            ("ebitda_variance", "EBITDA exceeded budget."),
            ("ebit_variance", "EBIT exceeded budget."),
            ("ebt_variance", "EBT exceeded budget."),
        )

        for field_name, message in favourable_profit_metrics:
            if self._get_number(variance, field_name) > 0:
                drivers.append(message)

        favourable_cost_metrics = (
            (
                "direct_cost_variance",
                "Direct cost was below budget.",
            ),
            (
                "sales_marketing_variance",
                "Sales and marketing expense was below budget.",
            ),
            (
                "other_opex_variance",
                "Other operating expense was below budget.",
            ),
            (
                "depreciation_variance",
                "Depreciation was below budget.",
            ),
            (
                "interest_variance",
                "Interest expense was below budget.",
            ),
        )

        for field_name, message in favourable_cost_metrics:
            if self._get_number(variance, field_name) < 0:
                drivers.append(message)

        if self._get_number(
            variance,
            "gross_margin_percentage_point_variance",
        ) > 0:
            drivers.append(
                "Gross margin improved compared with budget."
            )

        return drivers

    def _identify_risks(
        self,
        variance: Mapping[str, Any],
    ) -> list[str]:
        """
        Identify unfavourable P&L outcomes.
        """

        risks: list[str] = []

        unfavourable_profit_metrics = (
            ("revenue_variance", "Revenue was below budget."),
            (
                "gross_profit_variance",
                "Gross profit was below budget.",
            ),
            ("ebitda_variance", "EBITDA was below budget."),
            ("ebit_variance", "EBIT was below budget."),
            ("ebt_variance", "EBT was below budget."),
        )

        for field_name, message in unfavourable_profit_metrics:
            if self._get_number(variance, field_name) < 0:
                risks.append(message)

        unfavourable_cost_metrics = (
            (
                "direct_cost_variance",
                "Direct cost exceeded budget.",
            ),
            (
                "sales_marketing_variance",
                "Sales and marketing expense exceeded budget.",
            ),
            (
                "other_opex_variance",
                "Other operating expense exceeded budget.",
            ),
            (
                "depreciation_variance",
                "Depreciation exceeded budget.",
            ),
            (
                "interest_variance",
                "Interest expense exceeded budget.",
            ),
        )

        for field_name, message in unfavourable_cost_metrics:
            if self._get_number(variance, field_name) > 0:
                risks.append(message)

        if self._get_number(
            variance,
            "gross_margin_percentage_point_variance",
        ) < 0:
            risks.append(
                "Gross margin declined compared with budget."
            )

        return risks

    def _identify_management_attention(
        self,
        variance: Mapping[str, Any],
    ) -> list[str]:
        """
        Identify material P&L variances requiring management review.
        """

        items: list[str] = []

        material_metrics = (
            (
                "revenue_variance_percentage",
                "Review the material revenue variance.",
            ),
            (
                "direct_cost_variance_percentage",
                "Review the material direct-cost variance.",
            ),
            (
                "gross_profit_variance_percentage",
                "Review the material gross-profit variance.",
            ),
            (
                "sales_marketing_variance_percentage",
                "Review the material sales and marketing variance.",
            ),
            (
                "other_opex_variance_percentage",
                "Review the material other-OPEX variance.",
            ),
            (
                "ebitda_variance_percentage",
                "Review the material EBITDA variance.",
            ),
            (
                "ebit_variance_percentage",
                "Review the material EBIT variance.",
            ),
            (
                "ebt_variance_percentage",
                "Review the material EBT variance.",
            ),
        )

        for field_name, message in material_metrics:
            percentage = abs(
                self._get_number(variance, field_name)
            )

            if percentage >= self.MATERIAL_VARIANCE_PERCENTAGE:
                items.append(message)

        margin_variance = abs(
            self._get_number(
                variance,
                "gross_margin_percentage_point_variance",
            )
        )

        if margin_variance >= self.MATERIAL_MARGIN_MOVEMENT:
            items.append(
                "Review the material gross-margin movement."
            )

        return items

    def _build_profit_commentary(
        self,
        display_name: str,
        actual_value: float,
        budget_value: float,
        variance_value: float,
        variance_percentage: float,
    ) -> str:
        """
        Build commentary for a revenue or profit metric.
        """

        if variance_value > 0:
            direction = "above"
            classification = "favourable"
        elif variance_value < 0:
            direction = "below"
            classification = "unfavourable"
        else:
            return (
                f"{display_name} was in line with budget at "
                f"{self._format_currency(actual_value)}."
            )

        return (
            f"{display_name} was "
            f"{self._format_currency(actual_value)}, compared with "
            f"budget of {self._format_currency(budget_value)}. "
            f"It was {direction} budget by "
            f"{self._format_currency(abs(variance_value))}, representing "
            f"a {self._format_percentage(abs(variance_percentage))} "
            f"{classification} variance."
        )

    def _build_cost_commentary(
        self,
        display_name: str,
        actual_value: float,
        budget_value: float,
        variance_value: float,
        variance_percentage: float,
    ) -> str:
        """
        Build commentary for a cost or expense metric.
        """

        if variance_value < 0:
            direction = "below"
            classification = "favourable"
        elif variance_value > 0:
            direction = "above"
            classification = "unfavourable"
        else:
            return (
                f"{display_name} was in line with budget at "
                f"{self._format_currency(actual_value)}."
            )

        return (
            f"{display_name} was "
            f"{self._format_currency(actual_value)}, compared with "
            f"budget of {self._format_currency(budget_value)}. "
            f"It was {direction} budget by "
            f"{self._format_currency(abs(variance_value))}, representing "
            f"a {self._format_percentage(abs(variance_percentage))} "
            f"{classification} variance."
        )

    def _describe_profit_variance_inline(
        self,
        variance_value: float,
    ) -> str:
        """
        Create inline variance wording for revenue and profit metrics.
        """

        if variance_value > 0:
            return (
                ", exceeding budget by "
                f"{self._format_currency(variance_value)}"
            )

        if variance_value < 0:
            return (
                ", below budget by "
                f"{self._format_currency(abs(variance_value))}"
            )

        return ", in line with budget"

    def _describe_margin_variance_inline(
        self,
        variance_value: float,
    ) -> str:
        """
        Create inline variance wording for gross margin.
        """

        if variance_value > 0:
            return (
                ", improving by "
                f"{self._format_percentage_points(variance_value)}"
            )

        if variance_value < 0:
            return (
                ", declining by "
                f"{self._format_percentage_points(abs(variance_value))}"
            )

        return ", in line with budget"

    def _get_number(
        self,
        source: Mapping[str, Any],
        field_name: str,
    ) -> float:
        """
        Retrieve and validate a numeric P&L field.
        """

        if field_name not in source:
            raise ValueError(
                f"P&L summary is missing required field '{field_name}'."
            )

        value = source[field_name]

        if isinstance(value, bool):
            raise TypeError(
                f"P&L field '{field_name}' must be numeric."
            )

        try:
            return float(value)
        except (TypeError, ValueError) as exc:
            raise TypeError(
                f"P&L field '{field_name}' must be numeric."
            ) from exc

    def _copy_summary(
        self,
        summary: Mapping[str, Mapping[str, Any]],
    ) -> dict[str, Any]:
        """
        Create a shallow copy of the source P&L summary.
        """

        return {
            "actual": dict(summary["actual"]),
            "budget": dict(summary["budget"]),
            "variance": dict(summary["variance"]),
        }

    def _format_currency(
        self,
        value: Any,
    ) -> str:
        """
        Format currency using Indian business units.
        """

        numeric_value = float(value)
        absolute_value = abs(numeric_value)
        sign = "-" if numeric_value < 0 else ""

        if absolute_value >= 10_000_000:
            return (
                f"{sign}₹{absolute_value / 10_000_000:,.2f} crore"
            )

        if absolute_value >= 100_000:
            return (
                f"{sign}₹{absolute_value / 100_000:,.2f} lakh"
            )

        return f"{sign}₹{absolute_value:,.2f}"

    def _format_percentage(
        self,
        value: Any,
    ) -> str:
        """
        Format a percentage stored on a 0-to-100 scale.
        """

        return f"{float(value):,.2f}%"

    def _format_percentage_points(
        self,
        value: Any,
    ) -> str:
        """
        Format percentage-point movement.

        PnlAgent stores gross-margin variance directly on a 0-to-100
        percentage scale, so this method must not multiply by 100.
        """

        return f"{float(value):,.2f} percentage points"