-- Run as ACCOUNTADMIN once for this portfolio environment.
-- The application role is deliberately separated from object ownership.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS FINANCE_AI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS FINANCE_AI;
CREATE SCHEMA IF NOT EXISTS FINANCE_AI.RAW;
CREATE SCHEMA IF NOT EXISTS FINANCE_AI.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS FINANCE_AI.AUDIT;

CREATE ROLE IF NOT EXISTS FINANCE_AI_APP_ROLE;
GRANT USAGE ON WAREHOUSE FINANCE_AI_WH TO ROLE FINANCE_AI_APP_ROLE;
GRANT USAGE ON DATABASE FINANCE_AI TO ROLE FINANCE_AI_APP_ROLE;
GRANT USAGE ON SCHEMA FINANCE_AI.RAW TO ROLE FINANCE_AI_APP_ROLE;
GRANT USAGE ON SCHEMA FINANCE_AI.ANALYTICS TO ROLE FINANCE_AI_APP_ROLE;
GRANT USAGE ON SCHEMA FINANCE_AI.AUDIT TO ROLE FINANCE_AI_APP_ROLE;

USE WAREHOUSE FINANCE_AI_WH;
USE DATABASE FINANCE_AI;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT FINANCE_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null')
    DATE_FORMAT = 'AUTO'
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

CREATE STAGE IF NOT EXISTS FINANCE_CSV_STAGE
    FILE_FORMAT = FINANCE_CSV_FORMAT;

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID VARCHAR(32) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    PICKUP_CLUSTER VARCHAR(100),
    DROP_CLUSTER VARCHAR(100),
    VEHICLE_CATEGORY VARCHAR(100),
    ORDER_STATUS VARCHAR(40),
    FARE NUMBER(18, 2),
    COMMISSION_AMOUNT NUMBER(18, 2),
    PARTNER_PAYOUT NUMBER(18, 2),
    INCENTIVE NUMBER(18, 2),
    GOODWILL NUMBER(18, 2),
    DRY_RUN NUMBER(18, 2),
    SURGE NUMBER(18, 2),
    TRIP_DISTANCE_KM NUMBER(18, 2),
    DELIVERY_TIME_MINUTES NUMBER(10, 0)
);

CREATE TABLE IF NOT EXISTS CORPORATE_EXPENSES (
    MONTH DATE NOT NULL,
    SALES_MARKETING NUMBER(18, 2),
    OTHER_OPEX NUMBER(18, 2),
    DEPRECIATION NUMBER(18, 2),
    INTEREST NUMBER(18, 2)
);

CREATE TABLE IF NOT EXISTS BUDGET (
    MONTH DATE NOT NULL,
    VEHICLE_CATEGORY VARCHAR(100) NOT NULL,
    BUDGET_ORDERS NUMBER(18, 0),
    BUDGET_REVENUE NUMBER(18, 3),
    BUDGET_COGS NUMBER(18, 3)
);

CREATE TABLE IF NOT EXISTS BUDGET_CORPORATE_EXPENSES (
    MONTH DATE NOT NULL,
    SALES_MARKETING NUMBER(18, 2),
    OTHER_OPEX NUMBER(18, 2),
    DEPRECIATION NUMBER(18, 2),
    INTEREST NUMBER(18, 2)
);

CREATE TABLE IF NOT EXISTS BUSINESS_ASSUMPTIONS (
    MONTH DATE NOT NULL,
    ASSUMPTION VARCHAR(250),
    METRIC VARCHAR(100),
    IMPACT_TYPE VARCHAR(40),
    IMPACT_VALUE NUMBER(18, 4),
    DIRECTION VARCHAR(40),
    BUSINESS_REASON VARCHAR(2000)
);

GRANT SELECT ON ALL TABLES IN SCHEMA FINANCE_AI.RAW TO ROLE FINANCE_AI_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINANCE_AI.RAW TO ROLE FINANCE_AI_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FINANCE_AI.ANALYTICS TO ROLE FINANCE_AI_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FINANCE_AI.ANALYTICS TO ROLE FINANCE_AI_APP_ROLE;

