-- Upload the five local CSV files into @FINANCE_AI.RAW.FINANCE_CSV_STAGE
-- using Snowsight: Data > Add Data > Load files into a Stage.
-- Preserve these filenames, then run this worksheet.

USE WAREHOUSE FINANCE_AI_WH;
USE DATABASE FINANCE_AI;
USE SCHEMA RAW;

TRUNCATE TABLE ORDERS;
COPY INTO ORDERS
FROM @FINANCE_CSV_STAGE/sample_orders.csv
FILE_FORMAT = (FORMAT_NAME = FINANCE_CSV_FORMAT DATE_FORMAT = 'DD-MM-YYYY')
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE CORPORATE_EXPENSES;
COPY INTO CORPORATE_EXPENSES
FROM @FINANCE_CSV_STAGE/sample_corporate_expenses.csv
FILE_FORMAT = (FORMAT_NAME = FINANCE_CSV_FORMAT DATE_FORMAT = 'YYYY-MM')
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE BUDGET;
COPY INTO BUDGET
FROM @FINANCE_CSV_STAGE/sample_budget.csv
FILE_FORMAT = (FORMAT_NAME = FINANCE_CSV_FORMAT DATE_FORMAT = 'YYYY-MM')
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE BUDGET_CORPORATE_EXPENSES;
COPY INTO BUDGET_CORPORATE_EXPENSES
FROM @FINANCE_CSV_STAGE/sample_budget_corporate_expenses.csv
FILE_FORMAT = (FORMAT_NAME = FINANCE_CSV_FORMAT DATE_FORMAT = 'YYYY-MM')
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE BUSINESS_ASSUMPTIONS;
COPY INTO BUSINESS_ASSUMPTIONS
FROM @FINANCE_CSV_STAGE/business_assumptions.csv
FILE_FORMAT = (FORMAT_NAME = FINANCE_CSV_FORMAT DATE_FORMAT = 'YYYY-MM')
ON_ERROR = 'ABORT_STATEMENT';

-- Expected row counts: 500000, 12, 132, 12, and 10.
SELECT 'ORDERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM ORDERS
UNION ALL
SELECT 'CORPORATE_EXPENSES', COUNT(*) FROM CORPORATE_EXPENSES
UNION ALL
SELECT 'BUDGET', COUNT(*) FROM BUDGET
UNION ALL
SELECT 'BUDGET_CORPORATE_EXPENSES', COUNT(*) FROM BUDGET_CORPORATE_EXPENSES
UNION ALL
SELECT 'BUSINESS_ASSUMPTIONS', COUNT(*) FROM BUSINESS_ASSUMPTIONS;

SELECT
    MIN(ORDER_DATE) AS MIN_ORDER_DATE,
    MAX(ORDER_DATE) AS MAX_ORDER_DATE,
    COUNT(DISTINCT ORDER_ID) AS DISTINCT_ORDER_IDS,
    SUM(FARE) AS TOTAL_FARE,
    SUM(COMMISSION_AMOUNT) AS TOTAL_COMMISSION
FROM ORDERS;

SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'FINANCE_AI.RAW.ORDERS',
    START_TIME => DATEADD('hour', -2, CURRENT_TIMESTAMP())
));

