-- Run once as ACCOUNTADMIN for the Phase 4 request lifecycle.
USE ROLE ACCOUNTADMIN;

CREATE TABLE IF NOT EXISTS FINANCE_AI.AUDIT.FINANCE_REQUESTS (
    REQUEST_ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(255),
    QUESTION VARCHAR(5000) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    SELECTED_FLOW VARCHAR(100),
    ANSWER VARCHAR(16777216),
    ERROR_MESSAGE VARCHAR(2000),
    CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    STARTED_AT TIMESTAMP_TZ,
    COMPLETED_AT TIMESTAMP_TZ
);

GRANT SELECT, INSERT, UPDATE
ON TABLE FINANCE_AI.AUDIT.FINANCE_REQUESTS
TO ROLE FINANCE_AI_APP_ROLE;
